# Generated by Django 3.1.6 on 2021-05-14 16:44

from django.db import migrations, models
import django.db.models.deletion
import utils.upload
import utils.validators


class Migration(migrations.Migration):

    dependencies = [
        ('_auth', '0007_auto_20210514_2244'),
        ('events', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to=utils.upload.event_image_directory_path, validators=[utils.validators.validate_size, utils.validators.validate_extension], verbose_name='Изображение'),
        ),
        migrations.AlterField(
            model_name='event',
            name='manager',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='events', to='_auth.manager', verbose_name='Автор'),
        ),
    ]
