# Generated by Django 3.1.6 on 2021-04-22 19:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0005_auto_20210423_0106'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='image',
            field=models.ImageField(default=None, upload_to='images\\category', verbose_name='Изображение'),
        ),
        migrations.AlterField(
            model_name='flower',
            name='image',
            field=models.ImageField(default=None, upload_to='images\\flower', verbose_name='Изображение'),
        ),
    ]
