# Generated by Django 3.1.6 on 2021-04-26 19:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0011_auto_20210423_0114'),
    ]

    operations = [
        migrations.AlterField(
            model_name='flower',
            name='category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='flowers', to='product.category', verbose_name='Категория'),
        ),
        migrations.AlterField(
            model_name='flower',
            name='image',
            field=models.ImageField(default=None, upload_to='../flowershop/product/images/flower', verbose_name='Изображение'),
        ),
    ]
