# Generated by Django 3.1.6 on 2021-05-11 19:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0012_auto_20210427_0118'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='category',
            name='slug',
        ),
        migrations.RemoveField(
            model_name='flower',
            name='slug',
        ),
    ]
