# Generated by Django 3.1.6 on 2021-05-13 15:19

from django.db import migrations, models
import utils.upload
import utils.validators


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0014_auto_20210513_1935'),
    ]

    operations = [
        migrations.AlterField(
            model_name='flower',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to=utils.upload.product_image_directory_path, validators=[utils.validators.validate_size, utils.validators.validate_extension], verbose_name='Изображение'),
        ),
    ]
