# Generated by Django 3.1.6 on 2021-05-13 17:41

import _auth.models
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('_auth', '0002_auto_20210423_0034'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='customer',
            managers=[
                ('objects', _auth.models.MainUserManager()),
            ],
        ),

    ]
