# Generated by Django 3.1.6 on 2021-05-13 17:43

from django.db import migrations, models
import django.db.models.deletion
import utils.upload
import utils.validators


class Migration(migrations.Migration):

    dependencies = [
        ('_auth', '0003_auto_20210513_2341'),
    ]

    operations = [
        migrations.AddField(
            model_name='customer',
            name='location',
            field=models.CharField(blank=True, max_length=30),
        )


    ]
