# Generated by Django 3.1.6 on 2021-05-13 17:45

from django.db import migrations, models
import django.db.models.deletion
import utils.upload
import utils.validators


class Migration(migrations.Migration):

    dependencies = [
        ('_auth', '0004_auto_20210513_2343'),
    ]

    operations = [

        migrations.CreateModel(
            name='ManagerProfile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('avatar', models.ImageField(blank=True, default='C:\\Users\\User\\Desktop\\flowerShop\\flowerShop\\flowerShopBackend\\_auth\\images\\profile.png', null=True, upload_to=utils.upload.manager_image_directory_path, validators=[utils.validators.validate_size, utils.validators.validate_extension], verbose_name='Изображение')),
                ('bio', models.TextField(blank=True, max_length=500)),
                ('birth_date', models.DateField(blank=True, null=True)),
                ('manager', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='_auth.manager')),
            ],
            options={
                'verbose_name': 'Профиль Мэнеджера',
                'verbose_name_plural': 'Профили Мэнеджеров',
            },
        ),
        migrations.CreateModel(
            name='CustomerProfile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bio', models.TextField(blank=True, max_length=500)),
                ('birth_date', models.DateField(blank=True, null=True)),
                ('customer', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='_auth.customer')),
            ],
            options={
                'verbose_name': 'Профиль Покупателя',
                'verbose_name_plural': 'Профили Покупателей',
            },
        ),
        migrations.CreateModel(
            name='AdminProfile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('avatar', models.ImageField(blank=True, default='C:\\Users\\User\\Desktop\\flowerShop\\flowerShop\\flowerShopBackend\\_auth\\images\\profile.png', null=True, upload_to=utils.upload.admin_image_directory_path, validators=[utils.validators.validate_size, utils.validators.validate_extension], verbose_name='Изображение')),
                ('bio', models.TextField(blank=True, max_length=500)),
                ('birth_date', models.DateField(blank=True, null=True)),
                ('admin', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='_auth.admin')),
            ],
            options={
                'verbose_name': 'Профиль Админов',
                'verbose_name_plural': 'Профили Админов',
            },
        ),
    ]
