# Generated by Django 3.1.6 on 2021-05-14 16:44

import _auth.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('_auth', '0006_remove_admin_avatar'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='customer',
            managers=[
                ('objects', _auth.models.CustomerManager()),
            ],
        ),
        migrations.AlterModelManagers(
            name='manager',
            managers=[
                ('objects', _auth.models.ManagerManager()),
            ],
        ),
    ]
