# Generated by Django 3.1.6 on 2021-05-15 01:13

from django.db import migrations, models
import utils.upload
import utils.validators


class Migration(migrations.Migration):

    dependencies = [
        ('_auth', '0007_auto_20210514_2244'),
    ]

    operations = [
        migrations.AlterField(
            model_name='adminprofile',
            name='avatar',
            field=models.ImageField(blank=True, default='media/users/profile.png', null=True, upload_to=utils.upload.admin_image_directory_path, validators=[utils.validators.validate_size, utils.validators.validate_extension], verbose_name='Изображение'),
        ),
        migrations.AlterField(
            model_name='managerprofile',
            name='avatar',
            field=models.ImageField(blank=True, default='users/profile.png', null=True, upload_to=utils.upload.manager_image_directory_path, validators=[utils.validators.validate_size, utils.validators.validate_extension], verbose_name='Изображение'),
        ),
    ]
