# Generated by Django 3.1.6 on 2021-05-01 20:05

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('review', '0002_auto_20210502_0133'),
    ]

    operations = [
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.TextField(null=True, verbose_name='Описание')),
                ('created_date', models.DateField(default=datetime.date.today, verbose_name='Дата создания')),
            ],
        ),
        migrations.RemoveField(
            model_name='reply',
            name='created_date',
        ),
        migrations.RemoveField(
            model_name='reply',
            name='description',
        ),
        migrations.RemoveField(
            model_name='review',
            name='created_date',
        ),
        migrations.RemoveField(
            model_name='review',
            name='description',
        ),
    ]
