# Generated by Django 3.1.6 on 2021-05-01 20:22

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('_auth', '0002_auto_20210423_0034'),
        ('review', '0004_auto_20210502_0217'),
    ]

    operations = [
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.TextField(null=True, verbose_name='Описание')),
                ('created_date', models.DateField(default=datetime.date.today, verbose_name='Дата создания')),
            ],
        ),
        migrations.CreateModel(
            name='Review',
            fields=[
                ('comment_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='review.comment')),
                ('title', models.CharField(max_length=255, verbose_name='Наименование')),
                ('rate', models.PositiveIntegerField(default=0, verbose_name='Качество обслуживание')),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reviews', to='_auth.customer', verbose_name='Автор')),
            ],
            bases=('review.comment',),
        ),
    ]
