# Generated by Django 3.1.6 on 2021-05-01 20:37

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('_auth', '0002_auto_20210423_0034'),
        ('review', '0006_auto_20210502_0236'),
    ]

    operations = [
        migrations.CreateModel(
            name='Review',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.TextField(null=True, verbose_name='Описание')),
                ('created_date', models.DateField(default=datetime.date.today, verbose_name='Дата создания')),
                ('title', models.CharField(max_length=255, verbose_name='Наименование')),
                ('rate', models.PositiveIntegerField(default=0, verbose_name='Качество обслуживание')),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reviews', to='_auth.customer', verbose_name='Автор')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
