# Generated by Django 3.1.6 on 2021-05-01 20:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('review', '0008_reply'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Reply',
        ),
    ]
