# Generated by Django 3.1.6 on 2021-05-01 20:41

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('_auth', '0002_auto_20210423_0034'),
        ('review', '0009_delete_reply'),
    ]

    operations = [
        migrations.CreateModel(
            name='Reply',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.TextField(null=True, verbose_name='Описание')),
                ('created_date', models.DateField(default=datetime.date.today, verbose_name='Дата создания')),
                ('manager', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='replies', to='_auth.manager', verbose_name='Автор')),
                ('review', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='review.review', verbose_name='Отзыв')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
